image: chilio/laravel-dusk-ci:php-7.3

services:
  - mysql:5.7

# Helper function to setup private key to ssh to server
.init_opensshclient: &init_opensshclient |
  'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  eval $(ssh-agent -s)
  ssh-add <(echo "$SSH_PRIVATE_KEY")
  mkdir -p ~/.ssh
  '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test
  - dev
  - staging

unit_test:
  stage: test
  script:
    - cp .env.test.example .env
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit
    - php artisan dusk
  artifacts:
    paths:
      - tests/Browser/screenshots

deploy_dev:
  stage: dev
  script:
    - *init_opensshclient
    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA" --branch=dev
  environment:
    name: DEV
    url: https://larajs.site
  when: on_success
  only:
    - dev

deploy_staging:
  stage: staging
  script:
    - *init_opensshclient
    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA" --branch=staging
  environment:
    name: STAGING
    url: https://larajs.site
  when: on_success
  only:
    - staging
